name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'   
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  email_validator: ^2.1.17
  google_sign_in: ^6.2.1
  bloc: ^8.1.3
  go_router: ^13.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
